services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - $DOCKERDIR/appdata/qbittorrent/config:/config
      - $DOWNLOADDIR:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - $DOCKERDIR/appdata/homarr/configs:/app/data/configs
      - $DOCKERDIR/appdata/homarr/icons:/app/public/icons
      - $DOCKERDIR/appdata/homarr/data:/data
    ports:
      - '7575:7575'
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/appdata/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 1.0.0.1
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=$TZ
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    user: $PUID:$PGID
    volumes:
      - $DOCKERDIR/appdata/recyclarr/config:/config
    environment:
      - TZ=$TZ
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/appdata/radarr/config:/config
      - $MEDIADIR/Movies:/movies #optional
      - $DOWNLOADDIR:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/appdata/sonarr/config:/config
      - $MEDIADIR/TV:/tv #optional
      - $DOWNLOADDIR:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - $DOCKERDIR/appdata/plex/config:/config
      - $MEDIADIR/TV:/tv
      - $MEDIADIR/Movies:/movies
    restart: unless-stopped
  tailscale:
    container_name: tailscale
    hostname: tailscale-optiplex
    image: tailscale/tailscale:stable
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-exit-node
    volumes:
      - $DOCKERDIR/appdata/tailscale/lib:/var/lib # State data will be stored in this directory
      - /dev/net/tun:/dev/net/tun # Required for tailscale to work
    cap_add: # Required for tailscale to work
      - net_admin
      - sys_module
    command: tailscaled
    privileged: true
    restart: unless-stopped
    network_mode: host
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/appdata/bazarr/config:/config
      - $MEDIADIR/Movies:/movies #optional
      - $MEDIADIR/TV:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=$TZ
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - $DOCKERDIR/appdata/overseerr/config:/app/config
    restart: unless-stopped
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      ICON: "/data/FKOW logo.png"
      OVERRIDE_ICON: "TRUE"
      SEED: "flyingkows"
      SERVER_NAME: "Flying Kows"
      MOTD: "Harry's Minecraft Server"
      DIFFICULTY: "normal"
      RESOURCE_PACK: "https://download.mc-packs.net/pack/1befd1dc9e0d5158bbbe2a4b29f6ebad1fe7af81.zip"
      RESOURCE_PACK_SHA1: "1befd1dc9e0d5158bbbe2a4b29f6ebad1fe7af81"
      RESOURCE_PACK_ENFORCE: "TRUE"
    volumes:
      - $DOCKERDIR/appdata/mc/data:/data
  mc-backup:
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: mc
      # since this service waits for mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
    volumes:
      - $DOCKERDIR/appdata/mc/data:/data:ro
      - $DOCKERDIR/appdata/mc/backups:/backups
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/appdata/duplicati/config:/config
      - $DOCKERDIR/appdata-backup:/backups
      - $DOCKERDIR/appdata:/source
    ports:
      - 8200:8200
    restart: unless-stopped
