services:
  mc-offline:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
      TZ: $TZ
      SERVER_NAME: "Flying Kows Offline"
      MOTD: "Harry's Offline Modded Minecraft Server"
      DIFFICULTY: "normal"
      RESOURCE_PACK: "https://download.mc-packs.net/pack/1befd1dc9e0d5158bbbe2a4b29f6ebad1fe7af81.zip"
      RESOURCE_PACK_SHA1: "1befd1dc9e0d5158bbbe2a4b29f6ebad1fe7af81"
      RESOURCE_PACK_ENFORCE: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: SPIGOT
    volumes:
      - $DOCKERDIR/appdata/mc-offline/data:/data
  mc-offline-backup:
    image: itzg/mc-backup
    depends_on:
      mc-offline:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: mc-offline
      INITIAL_DELAY: 0
      PAUSE_IF_NO_PLAYERS: true
      TZ: $TZ
    volumes:
      - $DOCKERDIR/appdata/mc-offline/data:/data:ro
      - $DOCKERDIR/appdata/mc-offline/backups:/backups
  mc-offline-restore-backup:
    # Same image as mc, but any base image with bash and tar will work
    image: itzg/mc-backup
    restart: "no"
    entrypoint: restore-tar-backup
    volumes:
      # Must be same mount as mc service, needs to be writable
      - $DOCKERDIR/appdata/mc-backup/data:/data
      # Must be same mount as backups service, but can be read-only
      - $DOCKERDIR/appdata/mc-backup/backups:/backups:ro