services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TZ: $TZ
      ICON: "/data/FKOW logo.png"
      OVERRIDE_ICON: "TRUE"
      SEED: "flyingkows"
      SERVER_NAME: "Flying Kows"
      MOTD: "Harry's Minecraft Server"
      DIFFICULTY: "normal"
      RESOURCE_PACK: "https://download.mc-packs.net/pack/1befd1dc9e0d5158bbbe2a4b29f6ebad1fe7af81.zip"
      RESOURCE_PACK_SHA1: "1befd1dc9e0d5158bbbe2a4b29f6ebad1fe7af81"
      RESOURCE_PACK_ENFORCE: "TRUE"
    volumes:
      - $DOCKERDIR/appdata/mc/data:/data
  mc-backup:
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: mc
      # since this service waits for mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
      PAUSE_IF_NO_PLAYERS: true
      TZ: $TZ
    volumes:
      - $DOCKERDIR/appdata/mc/data:/data:ro
      - $DOCKERDIR/appdata/mc/backups:/backups
  mc-restore-backup:
    # Same image as mc, but any base image with bash and tar will work
    image: itzg/mc-backup
    restart: "no"
    entrypoint: restore-tar-backup
    volumes:
      # Must be same mount as mc service, needs to be writable
      - $DOCKERDIR/appdata/mc/data:/data
      # Must be same mount as backups service, but can be read-only
      - $DOCKERDIR/appdata/mc/backups:/backups:ro